class NotFoundError(Exception):
    pass


class AlreadyExists(Exception):
    pass
